version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=username
      - DB_PASSWORD=secretPassword
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
